reditClone/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/', views.signup, name="signup"),
    url(r'^login/', views.loginView, name="login"),
    url(r'^logout/', views.logoutView, name="logout"),
]

reditClone/posts/urls.py
from django.conf.urls import url
from . import views

app_name = 'posts'

urlpatterns = [
    url(r'^create/', views.create, name="create"),
    url(r'^(?P<pk>[0-9]+)/upvote', views.upvote, name='upvote'),
    url(r'^(?P<pk>[0-9]+)/downvote', views.downvote, name='downvote'),
]

reditClone/reditClone/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from posts import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^posts/', include('posts.urls')),
    url(r'^$', views.home, name="home"),
]

reditClone/accounts/models.py
from django.db import models

reditClone/posts/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=150)
    url = models.TextField()
    create_date = models.DateTimeField()
    author = models.ForeignKey(User)
    rating = models.IntegerField(default=0)

    def create_date_pretty(self):
        return self.create_date.strftime('%b %e %Y')

reditClone/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate, logout



def signup(request):
    if request.method == "POST":
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.get(username=request.POST['username'])
                return render(request, 'accounts/signup.html', {'error': "User like that already exists"})
            except User.DoesNotExist:
                user = User.objects.create_user(request.POST['username'], password=request.POST['password1'])
                login(request, user)
                return render(request, 'accounts/signup.html')
        else:
            return render(request, 'accounts/signup.html', {'error': "Your passwords don't match"})
    else:
        return render(request, 'accounts/signup.html')


def loginView(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST['next'])
            return redirect('home')
        else:
            return render(request, 'accounts/login.html', {'error': 'Wrong username or password'})
    else:
        return render(request, 'accounts/login.html')


def logoutView(request):
    if request.method == "POST":
        logout(request)
        return redirect('home')

reditClone/posts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from .models import Post


@login_required
def create(request):
    if request.method == 'POST':
        if request.POST['title'] and request.POST['url']:
            post = Post()
            post.title = request.POST['title']
            if request.POST['url'].startswith('http://') or request.POST['url'].startswith('https://'):
                post.url = request.POST['url']
            else:
                post.url = 'http://' + request.POST['url']
            post.create_date = timezone.datetime.now()
            post.author = request.user
            post.save()
            return redirect('home')
        else:
            return render(request, 'posts/create.html', {'error': 'You have to include both a title and a URL'})
    else:
        return render(request, 'posts/create.html')


def home(request):
    posts = Post.objects.order_by('-rating')
    return render(request, 'posts/home.html', {'posts': posts})


def upvote(request, pk):
    if request.method == 'POST':
        post = Post.objects.get(pk=pk)
        post.rating += 1
        post.save()
        return redirect('home')


def downvote(request, pk):
    if request.method == 'POST':
        post = Post.objects.get(pk=pk)
        post.rating -= 1
        post.save()
        return redirect('home')

reditClone/accounts/templates/accounts/login.html
<title> Login </title>
{% extends 'base.html' %}
  {% block content %}
  <h1> Log In!</h1>

  {% if error %}
  {{ error }}
  <br />
  <br />
  {% endif %}

    <form action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}

        {% if request.GET.next %}
        <input type="hidden" name="next" value="{{ request.GET.next }}" />
        {% endif %}

        Username:
        <br />
        <input type="text" name="username"/>
        <br />
        Password:
        <br/>
        <input type="password" name="password"/>
        <br />
         <br />
        <input class="btn btn-primary" type="submit" value="Login!"/>
    </form>

{% endblock %}

reditClone/accounts/templates/accounts/signup.html
<title> Signup </title>
{% extends 'base.html' %}
  {% block content %}
  <h1> Sign up!</h1>

  {% if error %}
  {{ error }}
  <br />
  <br />
  {% endif %}

    <form action="{% url 'accounts:signup' %}" method="POST">
        {% csrf_token %}
        Username:
        <br />
        <input type="text" name="username"/>
        <br />
        Password:
        <br/>
        <input type="password" name="password1"/>
        <br />
        Confirm Password:
        <br />
        <input type="password" name="password2"/>
        <br />
        <br />
        <input class="btn btn-primary" type="submit" value="Sign up!"/>
    </form>
 {% endblock %}

reditClone/posts/templates/posts/create.html
<title> Create post </title>
{% extends 'base.html' %}
  {% block content %}
  <h1>Add New Post</h1>

  {% if error %}
  {{ error }}
  <br />
  <br />
  {% endif %}

  <form action="{% url 'posts:create' %}" method="POST">
        {% csrf_token %}

        Title
        <br />
        <input type="text" name="title"/>
        <br />
        URL:
        <br/>
        <input type="text" name="url"/>
        <br />
        <br/>
        <input class="btn btn-primary" type="submit" value="Post"/>


  </form>
 {% endblock %}

reditClone/posts/templates/posts/home.html
<title> Homepage </title>
{% extends 'base.html' %}
  {% block content %}
  <h1> The homepage </h1>

  <a class="btn btn-primary" href="{% url 'posts:create' %}">Create New Post</a>
  <br/>
  <br/>
  {% if error %}
  {{ error }}
  <br />n
  <br />
  {% endif %}


  {% for post in posts.all %}



  <table>
    <tr>
      {% load static %}
      <td style="padding-right: 20px;"><a class="nav-link" href="#" onClick="document.getElementById('upvote{{ post.id }}').submit()">
        <img src="{% static 'posts/icon-arrow-up.png' %}"/></a>
        <br/>
        {{ post.rating }}
        <br/>
        <a class="nav-link" href="#" onClick="document.getElementById('downvote{{ post.id }}').submit()">
          <img src="{% static 'posts/icon-arrow-down.png' %}"/></a></td>
      <td>- <a href="{{post.url}}">{{post.title}}</a><br/></td>


    </tr>

  </table>

<form id="upvote{{ post.id }}" action="{% url 'posts:upvote' post.id %}" method="POST">
    {% csrf_token %}
    <input type="hidden"/>
  </form>


<form id="downvote{{ post.id }}" action="{% url 'posts:downvote' post.id %}" method="POST">
    {% csrf_token %}
    <input type="hidden"/>
  </form>

  <br />
  {{post.create_date_pretty}} by {{post.author.username}}
  <br />

  {% endfor %}


{% endblock %}

reditClone/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <title>My Blog </title>
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'home'%}">Reddit Clone</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse " id="navbarSupportedContent">
      <ul class="navbar-nav  ml-auto ">

            {% if user.is_authenticated %}
            <li class="nav-item active">
                <a class="nav-link" href="#" onClick="document.getElementById('logout').submit()">Logout <span class="sr-only">(current)</span></a>
                <form id="logout" method="POST" action="{% url 'accounts:logout' %}">
                {% csrf_token %}
                    <input type="hidden">
                </form>
            </li>
            {% else %}
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'accounts:login' %}">Login<span class="sr-only">(current)</span></a>
            </li>
            {% endif %}



      </ul>
    </div>
    </nav>

    <br />
    <br />

    <div class="container">
        {% block content %}

        {% endblock %}

     </div>


        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
      </body>



    <br />
    <br />

    </body>
</html>